name: Create bootJar

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3.1.0
   
    - name: Create bootJar
      run: ./gradlew bootJar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
